version: '1.0'
services:
  db-postgres:
    image: postgres:17
    restart: always
    container_name: dcoker-database-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bulletdb
networks:
  default:
    name: database-network
    external: true    